### PR TITLE
call arcore.destroy off of main thread Fixes #407 

### LINKED ISSUE #407: ANR due to arCore.destroy() being called on the main thread
## Problem
- getting Crashlytics reports of ANR and user reports of app hanging when closing AR activity
## Solution
- from ArCore Session documentation:
> Releases resources (a significant amount of native heap memory) used by an ARCore session.
Failure to close sessions explicitly may cause your app to run out of native memory and crash. If your app contains a single AR-enabled activity, it is recommended that you call close() from the activity's onDestroy method.
**This method will take several seconds to complete. To prevent blocking the main thread, call pause() on the main thread, and then call close() on a background thread.**

- use coroutine scope to call destroy off of MainThread

### PR DESCRIPTION
**Pull request by sameerjj**
## Problem
- getting Crashlytics reports of ANR and user reports of app hanging when closing AR activity
## Solution
- from ArCore Session documentation:
> Releases resources (a significant amount of native heap memory) used by an ARCore session.
Failure to close sessions explicitly may cause your app to run out of native memory and crash. If your app contains a single AR-enabled activity, it is recommended that you call close() from the activity's onDestroy method.
**This method will take several seconds to complete. To prevent blocking the main thread, call pause() on the main thread, and then call close() on a background thread.**

- use coroutine scope to call destroy off of MainThread

Fixes #407

### CODE REVIEW

**Comment by sameerjj** [comment]
Fixes #407

File: arsceneview/src/main/java/io/github/sceneview/ar/ARSceneView.kt [hunk 1]
```diff
@@ -573,6 +577,14 @@ open class ARSceneView @JvmOverloads constructor(
         super.destroy()
     }
 
+    fun destroyAr() {
```
Comment (ThomasGorisse) [inline arsceneview/src/main/java/io/github/sceneview/ar/ARSceneView.kt:580]:
```suggestion
    open fun destroyARCore() {
```

File: arsceneview/src/main/java/io/github/sceneview/ar/ARSceneView.kt [hunk 2]
```diff
@@ -561,7 +565,7 @@ open class ARSceneView @JvmOverloads constructor(
 
     override fun destroy() {
         if (!isDestroyed) {
-            arCore.destroy()
+            destroyAr()
```
Comment (ThomasGorisse) [inline arsceneview/src/main/java/io/github/sceneview/ar/ARSceneView.kt:568]:
```suggestion
            destroyARCore()
```

**Review by ThomasGorisse — CHANGES_REQUESTED** [review]

**Review by ThomasGorisse — APPROVED** [review]
Thanks !

**Comment by Antiglobalist** [comment]
@ThomasGorisse @sameerjj Hi !
I have updated SDK version to 2.0.4.
And i faced with NDK exception:
image

In my App flow I finish AR activity and start other one(Not AR)
I don't have any extra calls on Destroy state
image

I suppose it's happening cuz destroyARCore function is not thread safe inside now. And arCore.destroy() is calling twice
image
